"""Canonical discovery -> artifact -> deterministic replay demonstration."""

import json
import subprocess
from pathlib import Path

from src.agent.budget import DiscoveryBudget
from src.agent.discovery import DiscoveryAgent
from src.capability.replay import ReplayEngine
from src.surface.browser import BrowserSurface


START_URL = "http://127.0.0.1:5001"
ARTIFACT_PATH = "artifacts/lookup_savings_balance.json"
MANIFEST_PATH = "evidence/end_to_end_manifest.json"


def source_provenance():
    source_commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], text=True
    ).strip()
    worktree_clean = not subprocess.check_output(
        ["git", "status", "--porcelain"], text=True
    ).strip()
    return source_commit, worktree_clean


def write_manifest(source_commit, source_worktree_clean):
    manifest = {
        "source_commit": source_commit,
        "source_worktree_clean_at_start": source_worktree_clean,
        "command": "python -m tests.test_end_to_end",
        "discovery_mode": "model-driven",
        "replay_mode": "deterministic-no-llm",
        "artifact": ARTIFACT_PATH,
        "discovery_log": "evidence/end_to_end_discovery.jsonl",
        "replay_log": "evidence/end_to_end_replay.jsonl",
        "replay_screenshot": "evidence/end_to_end_replay.png",
        "transcript": "evidence/end_to_end_transcript.txt",
        "committed_evidence_complete": True,
        "provenance": (
            "Generated by the documented end-to-end command. A clean source "
            "worktree is required for exact commit provenance."
        ),
    }
    Path(MANIFEST_PATH).write_text(json.dumps(manifest, indent=2) + "\n")


def main():
    source_commit, source_worktree_clean = source_provenance()
    discovery_surface = BrowserSurface(headless=False)
    try:
        discovery_surface.start()
        discovery_surface.navigate(START_URL)
        agent = DiscoveryAgent(
            discovery_surface,
            budget=DiscoveryBudget(max_steps=8, max_llm_calls=8),
            log_path="evidence/end_to_end_discovery.jsonl",
        )
        agent.run(
            goal="Look up member 10023 and return their current savings balance.",
            artifact_path=ARTIFACT_PATH,
            parameters={"member_id": "10023"},
        )
    finally:
        discovery_surface.close()

    replay_surface = BrowserSurface(headless=False)
    try:
        replay_surface.start()
        engine = ReplayEngine(
            replay_surface,
            log_path="evidence/end_to_end_replay.jsonl",
        )
        capability = engine.load_capability(ARTIFACT_PATH)
        result = engine.run(capability, inputs={"member_id": "10024"})
        replay_surface.screenshot("evidence/end_to_end_replay.png")
        assert result.outputs == {"savings_balance": "$2150.75"}, result
        print("\nEND-TO-END PASS")
        print(f"Artifact: {ARTIFACT_PATH}")
        print(f"Replay outputs: {result.outputs}")
        write_manifest(source_commit, source_worktree_clean)
        print(f"Evidence manifest: {MANIFEST_PATH}")
    finally:
        replay_surface.close()


if __name__ == "__main__":
    main()
