from typing import Protocol

from src.agent.models import AgentAction, Observation


class Surface(Protocol):
    """Common boundary implemented by browser, desktop and terminal surfaces."""

    def start(self): ...
    def navigate(self, target: str): ...
    def observe(self) -> Observation: ...
    def execute(self, action: AgentAction, observation: Observation): ...
    def wait(self, milliseconds: int = 1000): ...
    def screenshot(self, path: str): ...
    def current_url(self) -> str: ...
    def page_title(self) -> str: ...
    def body_text(self) -> str: ...
    def find_target(self, target): ...
    def target_destination(self, target) -> str | None: ...
    def fill_target(self, target, value: str): ...
    def select_target(self, target, value: str): ...
    def click_target(self, target): ...
    def extract_labeled_value(self, label: str) -> str: ...
    def validation_errors(self) -> list[str]: ...
    def close(self): ...
