from typing import Protocol

from src.agent.models import AgentAction, Observation


class Surface(Protocol):
    """Common boundary implemented by browser, desktop and terminal surfaces."""

    def start(self): ...
    def navigate(self, target: str): ...
    def observe(self) -> Observation: ...
    def execute(self, action: AgentAction, observation: Observation): ...
    def wait(self, milliseconds: int = 1000): ...
    def screenshot(self, path: str): ...
    def close(self): ...
